services:
  app:
    image: zestawienia-mat:latest
    container_name: zestawienia-mat
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    env_file:
      - .env.docker
